development:
  clients:
    default:
      database: dj_master_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dj_master_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: dj_master_production
      hosts:
        - localhost:27017
